version: '3.9'

services:
  postgres:
    image: bitnami/postgresql:latest
    platform: linux/x86_64
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4:latest
    platform: linux/x86_64
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@docker.com
      - PGADMIN_DEFAULT_PASSWORD=postgres
    ports:
      - 5050:80
    volumes:
      - ./data/pgadmin-data:/var/lib/pgadmin
  
  redis:
    container_name: redis
    image: bitnami/redis:latest
    platform: linux/x86_64
    restart: always
    environment:
      - REDIS_USER=docker
      - REDIS_PASSWORD=docker
    volumes:
      - ./data/redis:/var/lib/redis/data
    ports:
      - 6379:6379

  mongo:
    container_name: mongodb
    image: mongo:latest
    platform: linux/x86_64
    ports:
      - 27017:27017
    volumes:
      - ./data/db/own/datadir:/data/db
    environment:
      - MONGO_HOST=0.0.0.0
      - MONGO_PORT=27017
      - MONGO_ADMIN=docker
      - MONGO_ADMINPASS=docker

  mongo-express:
    container_name: mongo-express
    image: mongo:latest
    platform: linux/x86_64
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=docker
      - ME_CONFIG_MONGODB_ADMINPASSWORD=docker
      - ME_CONFIG_MONGODB_URL=mongodb://root:password@mongo:27017/?authSource=admin
      - ME_CONFIG_BASICAUTH_USERNAME=docker
      - ME_CONFIG_BASICAUTH_PASSWORD=docker
    links:
      - mongo
 
  mysql:
    container_name: mysql
    image: bitnami/mysql:latest
    platform: linux/x86_64
    restart: always
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
      - MYSQL_ROOT_PASSWORD=docker
    volumes:
      - ./data/my-db:/var/lib/mysql
 
  nginx:
    container_name: nginx
    image: bitnami/nginx:latest
    platform: linux/x86_64
    restart: always
    environment:
      NGINX_HOST: ${NGINX_HOST}
    volumes:
      - ./data/nginx:/usr/share/nginx/html
    ports:
      - 8080:80
   
networks:
  default:
    name: development
    external: true
volumes:
  data: